name: Update Lotto Data

on:
  schedule:
    # Läuft mittwochs und samstags um 19:45 und 21:00 UTC
    - cron: '45 19,21 * * 3,6'
  workflow_dispatch: # Ermöglicht manuelles Starten per Klick zum Testen

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Scraper
        run: python fetch_lotto.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add lotto.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-Update Lottozahlen" && git push)
